### ISSUE TITLE
Issues on CF Push

### ISSUE THREAD

**Issue by cristianoub** [drnic/consul-docker-boshrelease#1]
Hi, I`m receiving this error message on CF push:
/tmp/buildpacks/8d05521164c8f2951cf85c9911dbf6f1/bin/detect: line 4: dirname /tmp/buildpacks/8d05521164c8f2951cf85c9911dbf6f1/bin/detect: No such file or directory
/tmp/buildpacks/8d05521164c8f2951cf85c9911dbf6f1/bin/detect: line 4: dirname : command not found
None of the buildpacks detected a compatible application
Exit status 222
Staging failed: Exited with status 222
Destroying container
Successfully destroyed container

Do U have Ideia how to fix this?

**Comment by drnic** [comment]
Repo moved to attic
